maynard.in: don't try to run weston under X on Raspbian

diff --git a/maynard.in b/maynard.in
--- a/maynard.in
+++ b/maynard.in
@@ -23,8 +23,14 @@ xdpyinfo > /dev/null 2>&1
 if [ "$?" = "0" ]; then
     # We are running under X, so let's assume this is a development
     # installation.
-    check_install
-    XDG_DATA_DIRS=$XDG_DATA_DIRS:$PREFIX/share/ $PREFIX/bin/weston
+    if ! cat /etc/os-release 2> /dev/null | grep 'ID=raspbian' > /dev/null; then
+        # Non-Raspbian, we can launch weston under X.
+        check_install
+        XDG_DATA_DIRS=$XDG_DATA_DIRS:$PREFIX/share/ $PREFIX/bin/weston
+    else
+        echo "You cannot run Maynard under X." >&2
+        exit 1
+    fi
 else
     weston-launch
 fi
